name: Deploy to EasyQue server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "$SERVER_IP" >> ~/.ssh/known_hosts

      - name: Setup SSH key
        run: |
          echo "${SSH_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Rsync code to server
        run: |
          rsync -avz --delete \
            --exclude ".git" \
            -e "ssh -i ~/.ssh/id_rsa" \
            ./ ${SERVER_USER}@${SERVER_IP}:${PROJECT_PATH}/

      - name: Install deps on server
        run: |
          ssh -i ~/.ssh/id_rsa ${SERVER_USER}@${SERVER_IP} <<'EOSSH'
          set -e
          cd ${PROJECT_PATH}
          # Node is already there; install modules and rebuild native deps (bcrypt)
          npm install --omit=dev
          npm rebuild bcrypt --build-from-source || true
          # Restart PM2
          pm2 restart easyque-backend --update-env || pm2 start index.js --name easyque-backend
          pm2 save
          EOSSH
    env:
      SERVER_IP: ${{ secrets.SERVER_IP }}
      SERVER_USER: ${{ secrets.SERVER_USER }}
      PROJECT_PATH: ${{ secrets.PROJECT_PATH }}
      SSH_KEY: ${{ secrets.SSH_KEY }}

