name: Deploy to Server

on:
  push:
    branches: [ main ]   # runs every time you push/commit to main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Copy repo to server
        uses: easingthemes/ssh-deploy@v4.1.8
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          TARGET: /opt/easyque-backend.new
          ARGS: "-rlgoDzvc --delete --exclude node_modules --exclude .env --exclude uploads"

      - name: Swap into place and restart
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            if [ -d /opt/easyque-backend ]; then rm -rf /opt/easyque-backend.bak && mv /opt/easyque-backend /opt/easyque-backend.bak; fi
            mv /opt/easyque-backend.new /opt/easyque-backend
            cd /opt/easyque-backend
            npm ci
            npm rebuild
            pm2 restart easyque-backend --update-env
